#!/usr/bin/env bash
# This script displays: "To infinity and beyond" indefinitely
# With a sleep 2 in between each iteration
# "I am invincible!!!" when receiving a SIGTERM signal

pkill -f 4-to_infinity_and_beyond
