#!/usr/bin/env bash
# This script displays numbers 1 to 20 using while loop:
# displays 4 then "bad luck from China" for 4th loop iteration
# displays 9 then "bad luck from Japan" for 9th loop iteration
# displays 17 then "bad luck from Italy" for 17th loop iteration

counter=1

while [ $counter -le 20 ]
do
	case $counter in
		4)
			echo $counter
			echo "bad luck from China"
			;;
		9)
			echo $counter
			echo "bad luck from Japan"
			;;
		17)
			echo $counter
			echo "bad luck from Italy"
			;;
		*)
			echo $counter
			;;
	esac
	((counter++))
done
