#!/usr/bin/env bash
# This script displays the content of the current directory in list format
# Where only the part of the name after the first dash is displayed

for file in *; do
	if [ -f "$file" ] && [[ "$file" == *-* ]]; then
		name_after_dash=$(echo "$file" | cut -d'-' -f2-)
		echo "$name_after_dash"
	fi
done
